<?php

/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

	Examples::AddPluginExampleFile("QFirebug", "qfirebug.php Introduction to Debugging with QFirebug");

?>
