<?php

/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

	QApplicationBase::$ClassFile['qautocompletetextboxbase'] = __PLUGINS__ . '/QAutoCompleteTextBox/QAutoCompleteTextBoxBase.class.php';
	QApplicationBase::$ClassFile['qajaxautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/QAjaxAutoCompleteTextBox.class.php';
	QApplicationBase::$ClassFile['qjavascriptautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/QJavaScriptAutoCompleteTextBox.class.php';
		
	QApplicationBase::$ClassFile['qfirebug'] = __PLUGINS__ . '/QFirebug/QFirebug.class.php';
	
	QApplicationBase::$ClassFile['qpromptdialog'] = __PLUGINS__ . '/DialogBoxes/QPromptDialog.class.php';
	QApplicationBase::$ClassFile['qtextboxpromptdialog'] = __PLUGINS__ . '/DialogBoxes/QTextBoxPromptDialog.class.php';
	QApplicationBase::$ClassFile['qradiobuttonpromptdialog'] = __PLUGINS__ . '/DialogBoxes/QRadioButtonPromptDialog.class.php';
	QApplicationBase::$ClassFile['qconfirmationdialog'] = __PLUGINS__ . '/DialogBoxes/QConfirmationDialog.class.php';

?>