<?php

/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

	Examples::AddPluginExampleFile("QAutoCompleteTextBox", "autocomplete.php * Auto-complete Textbox Example");
?>